linters:
  enable-all: true
  disable:
    - gosmopolitan
    - wsl
    - forbidigo
    - gochecknoglobals
    - depguard
    - godox
    - exportloopref # deprecated
    - gomnd # deprecated
    - execinquery # deprecated

    # on hold
    - gochecknoinits
    - exhaustruct
