linters:
  enable-all: true
  disable:
    - gosmopolitan
    - wsl
    - forbidigo
    - gochecknoglobals
    - depguard
    - exportloopref # deprecated

    # on hold
    - gochecknoinits
    - exhaustruct
