linters:
  enable-all: true
  disable:
    - gosmopolitan
    - wsl
    - forbidigo
    - gochecknoglobals
    - depguard
    - godox
    - exportloopref # deprecated

    # on hold
    - gochecknoinits
    - exhaustruct
    - testpackage

linters-settings:
  varnamelen:
    ignore-names:
      - err
      - tt
    ignore-decls:
      - t testing.T
      - e error

  mnd:
    ignored-functions:
      - 'cobra.ExactArgs'

issues:
  exclude-rules:
    - path: _test.go
      linters:
        - funlen
